services:
  frontend:
    build: .
    container_name: lista-precios-frontend
    ports:
      - "3002:5173"  # navegador -> 3002, contenedor -> 5173
    volumes:
      - .:/app
      - /app/node_modules

    restart: unless-stopped